Basic skeleton for blog app client rendering
raventid/react-blog pull request #1
Opened 2017-05-25 21:18 UTC by raventid

2017-05-26 08:14 UTC, blackleaden commented on container/BlogPage.js
> +          items.map(item => (React.createElement(BlogItem, item)))
В цикле при создании элементов требуется присваивать key. Для этого подойдет ключ "index" из твоего массива (лучше конечно назвать "id", точнее).

2017-05-26 08:18 UTC, blackleadsu requested changes

2017-05-26 08:18 UTC, blackleaden commented on container/BlogPage.js
> +          items.map(item => (React.createElement(BlogItem, item)))
В цикле при создании элементов требуется присваивать key. Для этого подойдет ключ "index" из твоего массива (лучше конечно назвать "id", точнее).

2017-05-26 08:18 UTC, blackleaden commented on ui/BlogItem.js
> +    { key: item.index },
здесь key не нужен

2017-05-26 08:18 UTC, blackleaden commented on ui/BlogItem.js
> +    React.createElement(TextBox, item)
Передавать все данные в TextBox избыточно, достаточно item.text

2017-05-27 19:04 UTC, blackleadsu approved these changes

2017-06-22 20:23 UTC, merged