Webpack + eslint + restructuring
raventid/react-blog pull request #4
Opened 2017-07-17 21:32 UTC by raventid

2017-07-17 21:36 UTC, raventid commented on webpack.config.js
> +     disableHostCheck: true,
Может быть я не очень умный, но без этого у меня не завелся вебпак.

2017-07-18 16:24 UTC, index01d requested changes
Запуск линтера `./node_modules/eslint/bin/eslint.js src/* --ext jsx,js` выдает массу стилистических проблем для исправления

2017-07-18 16:24 UTC, index01d commented on src/App.jsx
> +import BlogPage from './container/BlogPage';
Лучше использовать абсолютные пути вместо относительных, то есть `import BlogPage from 'containers/BlogPage'`

2017-07-18 21:10 UTC, raventid commented on src/App.jsx
> +import BlogPage from './container/BlogPage';
Айрбнбшный линтер говорит использовать абсолютный путь для внешних зависимостей, а если файл твой, то писать нужно с точкой. Если убрать точку, то он возмущенно покрасит это место красным)))

2017-07-20 08:40 UTC, index01d commented on src/App.jsx
> +import BlogPage from './container/BlogPage';
окей, дело барское:)

2017-07-20 18:43 UTC, merged