First redux implementation
raventid/react-blog pull request #6
Opened 2017-08-01 00:31 UTC by raventid

2017-08-01 10:19 UTC, index01d requested changes

2017-08-01 10:19 UTC, index01d commented on src/actions/Post.js
> +import request from 'superagent';
like лучше вытащить в отдельный модуль actions/Like

2017-08-01 10:19 UTC, index01d commented on src/actions/Posts.js
> +const errorLike = (id) => ({
дубль лайков тут явно лишний

2017-08-01 10:19 UTC, index01d commented on src/components/widgets/blog/Item.jsx
>      <Like {...{ id, likes: meta.likes, like }} />
можно выделить LikeContainer, чтобы не таскать коллбэки и данные по иерархии через свойства

2017-08-01 10:19 UTC, index01d commented on src/components/widgets/blog/elements/MetaInfo.jsx
> +    <div style={{ fontSize: '11px' }}>Created at: { moment(createdAt).format('LL') }</div>
форматирование даты лучше вытащить в хелпер, чтобы потом не менять формат в тысяче мест и например чтобы можно было легко избавиться от зависимости moment и поменять ее на что-нибудь другое

2017-08-01 10:19 UTC, index01d commented on src/components/widgets/blog/elements/MetaInfo.jsx
> +    <div style={{ fontSize: '11px' }}>Created at: { moment(createdAt).format('LL') }</div>
inline-стили крайне не приветствуются. Лучше создать css-модуль

2017-08-01 10:19 UTC, index01d commented on src/containers/ChartContainer.js
> +import { connect } from 'react-redux';
👍

2017-08-01 10:19 UTC, index01d commented on src/containers/ChartContainer.js
> +import _ from 'lodash';
лучше импортировать конкретные функции из lodash `import { map } from 'lodash'`

2017-08-01 22:59 UTC, raventid commented on src/components/widgets/blog/Item.jsx
>      <Like {...{ id, likes: meta.likes, like }} />
Я вот не совсем понял идею с этим контейнером. Метаданные например нужны не только Лайку, а что касается коллбэка, то да, пожалуй было бы неплохо поймать его повыше но я вот не уверен, что ради него одного стоит так делать. И в итоге все равно же из контейнера нам нужно будет прокинуть что-либо в Ю-ай компонент.

2017-08-01 23:03 UTC, raventid commented on src/actions/Post.js
> +import request from 'superagent';
Done

2017-08-02 06:27 UTC, index01d approved these changes

2017-08-02 21:04 UTC, merged